-- Row Level Security policies for AMINO RESTO BALI.
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.item_variants enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.orders_manual enable row level security;
alter table public.bookings enable row level security;
alter table public.reviews enable row level security;
alter table public.restaurant_settings enable row level security;
alter table public.gallery enable row level security;
alter table public.promos enable row level security;
alter table public.experience_leads enable row level security;
alter table public.delivery_drivers enable row level security;
alter table public.delivery_zones enable row level security;
alter table public.delivery_jobs enable row level security;
alter table public.delivery_handoff_checks enable row level security;
alter table public.delivery_proofs enable row level security;
alter table public.support_tickets enable row level security;
alter table public.guest_messages enable row level security;
alter table public.canned_responses enable row level security;
alter table public.recovery_actions enable row level security;
alter table public.quality_checklists enable row level security;
alter table public.allergen_matrix enable row level security;
alter table public.temperature_logs enable row level security;
alter table public.incident_reports enable row level security;
alter table public.training_records enable row level security;
alter table public.vendors enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.recipe_cost_cards enable row level security;
alter table public.cashflow_forecasts enable row level security;
alter table public.crm_segments enable row level security;
alter table public.marketing_campaigns enable row level security;
alter table public.voucher_codes enable row level security;
alter table public.broadcast_logs enable row level security;
alter table public.notifications enable row level security;
alter table public.loyalty_logs enable row level security;
alter table public.activity_logs enable row level security;
alter table public.contact_messages enable row level security;
alter table public.launch_readiness_items enable row level security;
alter table public.launch_notes enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin')
$$;

create policy "profiles self read" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "profiles self update" on public.profiles for update using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());
create policy "profiles admin insert" on public.profiles for insert with check (public.is_admin() or id = auth.uid());
create policy "profiles admin delete" on public.profiles for delete using (public.is_admin());

create policy "public categories read" on public.categories for select using (is_active = true or public.is_admin());
create policy "admin categories write" on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy "public menu read" on public.menu_items for select using (is_available = true or public.is_admin());
create policy "admin menu write" on public.menu_items for all using (public.is_admin()) with check (public.is_admin());
create policy "public variants read" on public.item_variants for select using (true);
create policy "admin variants write" on public.item_variants for all using (public.is_admin()) with check (public.is_admin());

create policy "orders owner admin read" on public.orders for select using (user_id = auth.uid() or public.is_admin());
create policy "orders owner insert" on public.orders for insert with check (user_id = auth.uid() or auth.uid() is not null);
create policy "orders owner pending update" on public.orders for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "orders admin delete" on public.orders for delete using (public.is_admin());
create policy "order items owner admin read" on public.order_items for select using (public.is_admin() or exists(select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));
create policy "order items owner insert" on public.order_items for insert with check (public.is_admin() or exists(select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));
create policy "order items admin update" on public.order_items for update using (public.is_admin()) with check (public.is_admin());
create policy "manual owner admin all" on public.orders_manual for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

create policy "bookings owner admin read" on public.bookings for select using (user_id = auth.uid() or public.is_admin());
create policy "bookings insert logged in" on public.bookings for insert with check (auth.uid() is not null);
create policy "bookings owner admin update" on public.bookings for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "bookings admin delete" on public.bookings for delete using (public.is_admin());

create policy "visible reviews public read" on public.reviews for select using (is_visible = true or user_id = auth.uid() or public.is_admin());
create policy "reviews logged in insert" on public.reviews for insert with check (auth.uid() is not null and user_id = auth.uid());
create policy "reviews owner update" on public.reviews for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "reviews admin delete" on public.reviews for delete using (public.is_admin());

create policy "settings public read" on public.restaurant_settings for select using (true);
create policy "settings admin write" on public.restaurant_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "gallery public read" on public.gallery for select using (true);
create policy "gallery admin write" on public.gallery for all using (public.is_admin()) with check (public.is_admin());
create policy "promos public active read" on public.promos for select using (is_active = true or public.is_admin());
create policy "promos admin write" on public.promos for all using (public.is_admin()) with check (public.is_admin());
create policy "experience leads owner admin read" on public.experience_leads for select using (user_id = auth.uid() or public.is_admin());
create policy "experience leads logged in insert" on public.experience_leads for insert with check (auth.uid() is not null and (user_id = auth.uid() or user_id is null));
create policy "experience leads owner admin update" on public.experience_leads for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "experience leads admin delete" on public.experience_leads for delete using (public.is_admin());
create policy "delivery drivers admin all" on public.delivery_drivers for all using (public.is_admin()) with check (public.is_admin());
create policy "delivery zones public read" on public.delivery_zones for select using (active = true or public.is_admin());
create policy "delivery zones admin all" on public.delivery_zones for all using (public.is_admin()) with check (public.is_admin());
create policy "delivery jobs admin all" on public.delivery_jobs for all using (public.is_admin()) with check (public.is_admin());
create policy "delivery handoff admin all" on public.delivery_handoff_checks for all using (public.is_admin()) with check (public.is_admin());
create policy "delivery proofs admin all" on public.delivery_proofs for all using (public.is_admin()) with check (public.is_admin());
create policy "support tickets admin all" on public.support_tickets for all using (public.is_admin()) with check (public.is_admin());
create policy "guest messages admin all" on public.guest_messages for all using (public.is_admin()) with check (public.is_admin());
create policy "canned responses public read" on public.canned_responses for select using (is_active = true or public.is_admin());
create policy "canned responses admin all" on public.canned_responses for all using (public.is_admin()) with check (public.is_admin());
create policy "recovery actions admin all" on public.recovery_actions for all using (public.is_admin()) with check (public.is_admin());
create policy "quality checklists admin all" on public.quality_checklists for all using (public.is_admin()) with check (public.is_admin());
create policy "allergen public read" on public.allergen_matrix for select using (true);
create policy "allergen admin all" on public.allergen_matrix for all using (public.is_admin()) with check (public.is_admin());
create policy "temperature logs admin all" on public.temperature_logs for all using (public.is_admin()) with check (public.is_admin());
create policy "incident reports admin all" on public.incident_reports for all using (public.is_admin()) with check (public.is_admin());
create policy "training records admin all" on public.training_records for all using (public.is_admin()) with check (public.is_admin());
create policy "vendors admin all" on public.vendors for all using (public.is_admin()) with check (public.is_admin());
create policy "purchase orders admin all" on public.purchase_orders for all using (public.is_admin()) with check (public.is_admin());
create policy "recipe cost cards admin all" on public.recipe_cost_cards for all using (public.is_admin()) with check (public.is_admin());
create policy "cashflow forecasts admin all" on public.cashflow_forecasts for all using (public.is_admin()) with check (public.is_admin());
create policy "growth segments admin all" on public.crm_segments for all using (public.is_admin()) with check (public.is_admin());
create policy "growth campaigns admin all" on public.marketing_campaigns for all using (public.is_admin()) with check (public.is_admin());
create policy "voucher public active read" on public.voucher_codes for select using (status = 'active' or public.is_admin());
create policy "voucher admin all" on public.voucher_codes for all using (public.is_admin()) with check (public.is_admin());
create policy "broadcast logs admin all" on public.broadcast_logs for all using (public.is_admin()) with check (public.is_admin());
create policy "notifications owner audience admin read" on public.notifications for select using (user_id = auth.uid() or audience in ('all', 'customer') or public.is_admin());
create policy "notifications owner update read" on public.notifications for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "notifications logged in insert" on public.notifications for insert with check (auth.uid() is not null or public.is_admin());
create policy "notifications admin all" on public.notifications for all using (public.is_admin()) with check (public.is_admin());
create policy "loyalty owner admin read" on public.loyalty_logs for select using (user_id = auth.uid() or public.is_admin());
create policy "loyalty admin write" on public.loyalty_logs for all using (public.is_admin()) with check (public.is_admin());
create policy "activity admin read" on public.activity_logs for select using (public.is_admin());
create policy "activity admin write" on public.activity_logs for all using (public.is_admin()) with check (public.is_admin());

create policy "contact messages public insert" on public.contact_messages for insert with check (true);
create policy "contact messages admin read" on public.contact_messages for select using (public.is_admin());
create policy "contact messages admin update" on public.contact_messages for update using (public.is_admin()) with check (public.is_admin());
create policy "contact messages admin delete" on public.contact_messages for delete using (public.is_admin());
create policy "launch readiness admin all" on public.launch_readiness_items for all using (public.is_admin()) with check (public.is_admin());
create policy "launch notes admin all" on public.launch_notes for all using (public.is_admin()) with check (public.is_admin());
