-- Extended AMINO RESTO BALI seed data for richer demo and production bootstrap.
-- Run after schema.sql and seed-menu.sql.

insert into public.categories (name, slug, sort_order)
values
  ('Coffee & Tea', 'coffee-tea', 6),
  ('Kids', 'kids', 7)
on conflict (slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = true;

insert into public.menu_items (
  category_id,
  name,
  slug,
  description,
  price,
  calories,
  protein,
  fat,
  carbs,
  is_recommended,
  is_best_seller,
  is_new,
  is_vegan,
  is_gluten_free,
  is_spicy
)
values
  (
    (select id from public.categories where slug = 'breakfast'),
    'Bali Sunrise Omelette',
    'bali-sunrise-omelette',
    'Free-range eggs, spinach, goat cheese, tomato relish, garden herbs.',
    72000,
    390,
    24,
    25,
    18,
    true,
    false,
    true,
    false,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'breakfast'),
    'Canggu Granola Parfait',
    'canggu-granola-parfait',
    'House granola, coconut yoghurt, banana, honey, berries, cacao nibs.',
    64000,
    430,
    11,
    17,
    61,
    false,
    false,
    false,
    true,
    false,
    false
  ),
  (
    (select id from public.categories where slug = 'breakfast'),
    'Protein Pancake Stack',
    'protein-pancake-stack',
    'Oat pancakes, whey or pea protein, peanut butter, grilled banana.',
    84000,
    610,
    34,
    21,
    72,
    true,
    true,
    false,
    false,
    false,
    false
  ),
  (
    (select id from public.categories where slug = 'main-menu'),
    'Amino Chicken Satay Bowl',
    'amino-chicken-satay-bowl',
    'Charcoal chicken satay, red rice, cucumber, lawar salad, peanut sauce.',
    104000,
    720,
    43,
    31,
    68,
    true,
    true,
    false,
    false,
    false,
    false
  ),
  (
    (select id from public.categories where slug = 'main-menu'),
    'Seared Mahi Mahi Coconut Curry',
    'seared-mahi-mahi-coconut-curry',
    'Line-caught mahi mahi, turmeric coconut curry, greens, jasmine rice.',
    148000,
    680,
    46,
    29,
    55,
    false,
    false,
    false,
    false,
    true,
    true
  ),
  (
    (select id from public.categories where slug = 'main-menu'),
    'Jackfruit Rendang Tacos',
    'jackfruit-rendang-tacos',
    'Slow-cooked jackfruit rendang, pickled shallot, avocado, corn tortilla.',
    93000,
    540,
    13,
    24,
    67,
    false,
    false,
    true,
    true,
    false,
    true
  ),
  (
    (select id from public.categories where slug = 'main-menu'),
    'Wagyu Truffle Nasi Goreng',
    'wagyu-truffle-nasi-goreng',
    'Premium beef, truffle aroma, organic egg, cucumber pickle, prawn cracker.',
    168000,
    790,
    39,
    36,
    76,
    false,
    true,
    true,
    false,
    false,
    false
  ),
  (
    (select id from public.categories where slug = 'healthy-bowl'),
    'Ocean Poke Bowl',
    'ocean-poke-bowl',
    'Tuna, avocado, wakame, edamame, brown rice, sesame yuzu dressing.',
    118000,
    610,
    37,
    24,
    60,
    true,
    false,
    false,
    false,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'healthy-bowl'),
    'Green Goddess Quinoa Bowl',
    'green-goddess-quinoa-bowl',
    'Quinoa, roasted pumpkin, kale, avocado, sprouts, basil tahini dressing.',
    96000,
    570,
    18,
    29,
    64,
    false,
    false,
    false,
    true,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'healthy-bowl'),
    'Amino Athlete Bowl',
    'amino-athlete-bowl',
    'Grilled chicken, sweet potato, broccoli, edamame, egg, miso dressing.',
    112000,
    690,
    51,
    22,
    64,
    false,
    true,
    false,
    false,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'desserts'),
    'Dark Chocolate Avocado Mousse',
    'dark-chocolate-avocado-mousse',
    'Avocado cacao mousse, sea salt, coconut whip, toasted almond.',
    62000,
    340,
    7,
    23,
    31,
    false,
    false,
    false,
    true,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'desserts'),
    'Mango Sticky Black Rice',
    'mango-sticky-black-rice',
    'Black rice, coconut cream, mango, sesame brittle, pandan syrup.',
    59000,
    410,
    6,
    12,
    71,
    false,
    false,
    false,
    true,
    false,
    false
  ),
  (
    (select id from public.categories where slug = 'desserts'),
    'Lemongrass Cheesecake Jar',
    'lemongrass-cheesecake-jar',
    'Cream cheese, lemongrass, biscuit crumble, passion fruit glaze.',
    66000,
    460,
    8,
    27,
    47,
    false,
    false,
    true,
    false,
    false,
    false
  ),
  (
    (select id from public.categories where slug = 'drinks'),
    'Cold Brew Coconut Cloud',
    'cold-brew-coconut-cloud',
    'Slow cold brew coffee, coconut foam, palm sugar, cinnamon dust.',
    56000,
    190,
    2,
    8,
    28,
    false,
    false,
    true,
    false,
    false,
    false
  ),
  (
    (select id from public.categories where slug = 'drinks'),
    'Hibiscus Ginger Sparkle',
    'hibiscus-ginger-sparkle',
    'Hibiscus tea, ginger, lime, sparkling water, mint, no refined sugar.',
    46000,
    90,
    0,
    0,
    22,
    false,
    false,
    false,
    true,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'drinks'),
    'Matcha Moringa Frappe',
    'matcha-moringa-frappe',
    'Ceremonial matcha, moringa, oat milk, vanilla, ice-blended creaminess.',
    62000,
    240,
    5,
    9,
    35,
    false,
    false,
    false,
    true,
    false,
    false
  ),
  (
    (select id from public.categories where slug = 'coffee-tea'),
    'Single Origin V60 Bali Kintamani',
    'single-origin-v60-bali-kintamani',
    'Manual brew with citrus aroma, brown sugar notes, clean finish.',
    52000,
    5,
    0,
    0,
    1,
    false,
    false,
    true,
    true,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'coffee-tea'),
    'Jasmine Kombucha Tea',
    'jasmine-kombucha-tea',
    'Lightly fermented jasmine green tea, probiotic sparkle, floral finish.',
    54000,
    70,
    0,
    0,
    16,
    false,
    false,
    false,
    true,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'kids'),
    'Mini Chicken Rice Plate',
    'mini-chicken-rice-plate',
    'Grilled chicken, steamed rice, carrot sticks, cucumber, mild sauce.',
    58000,
    420,
    28,
    12,
    48,
    false,
    false,
    false,
    false,
    true,
    false
  ),
  (
    (select id from public.categories where slug = 'kids'),
    'Banana Cocoa Smoothie',
    'banana-cocoa-smoothie',
    'Banana, cocoa, oat milk, dates, chia, no refined sugar.',
    44000,
    260,
    6,
    7,
    46,
    false,
    false,
    false,
    true,
    false,
    false
  )
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  calories = excluded.calories,
  protein = excluded.protein,
  fat = excluded.fat,
  carbs = excluded.carbs,
  is_recommended = excluded.is_recommended,
  is_best_seller = excluded.is_best_seller,
  is_new = excluded.is_new,
  is_vegan = excluded.is_vegan,
  is_gluten_free = excluded.is_gluten_free,
  is_spicy = excluded.is_spicy,
  updated_at = now();

insert into public.promos (
  title,
  description,
  code,
  discount_type,
  discount_value,
  valid_from,
  valid_to,
  is_active
)
values
  (
    'Botanical Brunch Set',
    'Free detox shot for breakfast orders above Rp 150.000.',
    'AMINOBRUNCH',
    'amount',
    0,
    '2026-05-01 00:00:00+00',
    '2026-06-30 23:59:59+00',
    true
  ),
  (
    'Natural Luxury Dinner',
    'Complimentary dessert for table booking 4+ guests.',
    'AMINODINNER',
    'amount',
    0,
    '2026-05-01 00:00:00+00',
    '2026-07-15 23:59:59+00',
    true
  )
on conflict (code) do update set
  title = excluded.title,
  description = excluded.description,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to,
  is_active = excluded.is_active;
